version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
           command: pip install .
           name: install
  test:
    executor: python/default
    steps:
      - run:
          command: python -m pytest tests/tests.py::TestInternal
          name: Test

workflows:
  main:
    jobs:
      - build
      - test
